name: root
dependencies:
- anaconda-client=1.2.1=py27_0
- biopython=1.66=np110py27_0
- cairo=1.12.18=6
- clyent=1.2.0=py27_0
- conda=3.19.0=py27_0
- conda-env=2.4.5=py27_0
- cycler=0.9.0=py27_0
- decorator=4.0.6=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- hdf5=1.8.15.1=2
- ipython=4.0.2=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mpld3=0.2=py27_0
- numpy=1.10.2=py27_0
- openblas=0.2.14=3
- openssl=1.0.2f=0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=8.0.1=py27_0
- pixman=0.32.6=0
- pycairo=1.10.0=py27_0
- pycosat=0.6.1=py27_0
- pycrypto=2.6.1=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pysam=0.8.4=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- qt=4.8.7=1
- readline=6.2=2
- requests=2.9.1=py27_0
- setuptools=19.4=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- traitlets=4.1.0=py27_0
- wheel=0.26.0=py27_1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - stevedore==0.15
  - virtualenv==1.11.6
  - virtualenv-clone==0.2.5
  - virtualenvwrapper==4.3.1

