"""
Simple script to get transcript infromation from the database generated by
Cufflinks 
"""
import optparse, sys, csv, os, sqlite3
from pySeq.common_funcs import regionParse


def main():
    p = optparse.OptionParser(__doc__)
    p.add_option("-D", "--debug", action="store_true", dest="D", help="debug")
    p.add_option("-N", "--novel", action="store_true", dest="novel",\
	    help="Only check at novel loci")
    p.add_option("-i", "--identifier", dest="i",\
	    help="Identifier to use")
    p.add_option("-o", "--outupt", dest="o",\
	    help="Input database")
    options, args = p.parse_args()

    
    if options.o:
	conn = sqlite3.connect(options.o) 
    else:
	conn = sqlite3.connect('/gen_local/hsuj/temp/masked.data')
    t = (args[0], )
    
    c = conn.cursor()
    c.execute('''SELECT * FROM transcripts WHERE tcons=?''', t)
    res = c.fetchmany()
    for i in res:
	print(i)
	print(min(map(int, i[3].split(','))))
	print(max(map(int, i[4].split(','))))
    

if __name__ == '__main__':
    main()
